services:
  secured-app:
    build:
      context: ../../..
      dockerfile: labs/LLM08_Data-Poisoning/Secured-Version/Dockerfile
    ports:
      - "8502:8501"
    environment:
      OLLAMA_BASE_URL: http://ollama-service:11434
    depends_on:
      - ollama-service

  ollama-service:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull llama3 && wait"

volumes:
  ollama_data:
